name: a11y_pjt
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  file_selector: ^0.8.4+3
  firebase_core: ^1.19.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  json_serializable: ^6.3.1
  rxdart: ^0.27.5
  syncfusion_flutter_core: ^20.2.39
  syncfusion_flutter_datagrid: ^20.2.39
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
