name: a11y_pjt
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  code_text_field: ^1.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dio2: ^5.0.0-nullsafety
  drag_and_drop_lists: ^0.3.2+2
  duration_picker: ^1.0.1
  easy_sidemenu: ^0.3.1
  eva_icons_flutter: ^3.1.0
  file_selector: ^0.8.4+3
  firebase_core: ^1.19.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get: 4.6.5
  get_storage: ^2.0.3
  getwidget: ^3.0.1
  google_fonts: ^3.0.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  material_design_icons_flutter: ^5.0.6996
  resizable_widget: ^1.0.5
  retrofit: ^3.0.1+1
  rxdart: ^0.27.5
  syncfusion_flutter_calendar: ^20.2.39
  syncfusion_flutter_core: ^20.2.39
  syncfusion_flutter_datagrid: ^20.2.39
  time_range_picker: ^2.2.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  retrofit_generator: ^4.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
