// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfeKywMxbmFA6rNSmO7bQhIhYICVkxKDQ',
    appId: '1:532079373473:web:4119d0abe649afe7b754e0',
    messagingSenderId: '532079373473',
    projectId: 'a11y-pjt',
    authDomain: 'a11y-pjt.firebaseapp.com',
    storageBucket: 'a11y-pjt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3VtM516CAOiHACAJwG-b77POPQwluvFY',
    appId: '1:532079373473:android:ce991ff0d654046ab754e0',
    messagingSenderId: '532079373473',
    projectId: 'a11y-pjt',
    storageBucket: 'a11y-pjt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_cy7b35eUSVY7AipKOy4nmDkXqvBe6YQ',
    appId: '1:532079373473:ios:261751cb9a75a53cb754e0',
    messagingSenderId: '532079373473',
    projectId: 'a11y-pjt',
    storageBucket: 'a11y-pjt.appspot.com',
    iosClientId: '532079373473-5nt47popc7tgm3opntdjskngvdaj8hn1.apps.googleusercontent.com',
    iosBundleId: 'fr.benabdelaziz.a11yPjt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_cy7b35eUSVY7AipKOy4nmDkXqvBe6YQ',
    appId: '1:532079373473:ios:261751cb9a75a53cb754e0',
    messagingSenderId: '532079373473',
    projectId: 'a11y-pjt',
    storageBucket: 'a11y-pjt.appspot.com',
    iosClientId: '532079373473-5nt47popc7tgm3opntdjskngvdaj8hn1.apps.googleusercontent.com',
    iosBundleId: 'fr.benabdelaziz.a11yPjt',
  );
}
